SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM 
    ITEM_INFO i
JOIN 
    ITEM_TREE t ON t.ITEM_ID = i.ITEM_ID
LEFT JOIN 
    ITEM_TREE c ON c.PARENT_ITEM_ID = t.ITEM_ID
WHERE 
    c.ITEM_ID IS NULL     
ORDER BY 
    i.ITEM_ID DESC;
