SELECT p.PRODUCT_ID as PRODUCT_ID, p.PRODUCT_NAME, sum(p.PRICE * o.AMOUNT)TOTAL_SALES
from FOOD_PRODUCT as p
join FOOD_ORDER as o
on p.PRODUCT_ID = o.PRODUCT_ID
where o.PRODUCE_DATE like '2022-05-%'
group by PRODUCT_ID
order by TOTAL_SALES desc,PRODUCT_ID;
